#!/bin/sh

TMPFOLDER=/tmp/single_user.$RANDOM

if [ -f /etc/boot.conf ]; then
	grep '^boot -s$' /etc/boot.conf 2> /dev/null 1>&2
	if [ $? == 0 ]; then
		mount -uw /
		mkdir $TMPFOLDER
		grep -v '^boot -s$' /etc/boot.conf > $TMPFOLDER/boot.conf
		rm /etc/boot.conf
		mv $TMPFOLDER/boot.conf /etc
		rm -rf $TMPFOLDER
		echo boot >> /etc/boot.conf
		mount -ur /
	else
		exit 1
	fi
fi
