#!/bin/sh

TMPFOLDER=/tmp/single_user.$RANDOM

SINGLE_USER_MODE(){
echo "boot -s" >> /etc/boot.conf
}

if [ -f /etc/boot.conf ]; then

	grep '^boot -s$' /etc/boot.conf 2> /dev/null 1>&2

	if [ $? == 0 ]; then
		exit 0
	fi

	grep '^boot' /etc/boot.conf 2> /dev/null 1>&2

	if [ $? == 1 ]; then
		SINGLE_USER_MODE
	else
		mkdir $TMPFOLDER
		sed "s/^boot.*/boot -s/g" /etc/boot.conf > $TMPFOLDER/boot.conf
		rm /etc/boot.conf
		mv $TMPFOLDER/boot.conf /etc
		rm -rf $TMPFOLDER
	fi
else
	SINGLE_USER_MODE
fi
