#!/bin/sh

PLAY_THE_JOB(){
/usr/sbin/rcctl stop ntpd
/usr/sbin/rcctl set ntpd flags -s
/usr/sbin/rcctl start ntpd
/usr/sbin/rcctl stop sndiod
/usr/sbin/rcctl disable sndiod

[ -f /etc/pkg.conf ] || echo installpath=ftp2.fr.openbsd.org > /etc/pkg.conf
pkg_add rsync--

cd /usr/local/sbin && ftp https://stable.mtier.org/openup
chmod +x /usr/local/sbin/openup

echo 1 > /etc/mfs.state
}

if [ -f /etc/mfs.state ]; then
	exit 1
else
	PLAY_THE_JOB
fi
